# This is like Makefiles, but easier and trully cross-platform. See https://github.com/go-task/task
version: '2'

tasks:
  default:
    deps: [update, copy]

  update:
    cmds:
      - echo "TODO UPDATE FILTER..."
    silent: true

  copy:
    desc: "copies filter file to game folder"
    cmds:
      - copy "LE_FILTER.filter" "C:\Users\dev\Documents\My Games\Path of Exile\LE_FILTER.filter"